### PR TITLE
Fm band title

### PR DESCRIPTION
**Pull request by Feven90**
- On home page, you should see the band's name on the top middle area. 
- I have used font-type 'Oswald' for the band name, if you have any other font type suggestion pls let me know.
- And the font for the whole body should change when you resize the screen. 
- last, I have deleted .navul li { } from css file which was empty.

### CODE REVIEW

**Comment by shanedwilson** [comment]
Should we go for something really, really stupid like:
https://fonts.google.com/specimen/Metal+Mania

**Comment by shanedwilson** [comment]
Also, let's make the font size 3em or more. It should command the page, yes?

**Comment by Feven90** [comment]
@shanedwilson it looks so much better with your suggestion :+1:

**Comment by shanedwilson** [comment]
HAAAAA! "Better" is subjective, I suppose. That being said, my vote is to keep playing with the font-size until it takes up more of the screen. Make it offensive. We can do a media query later so that it's smaller for mobile, if we have time.

**Comment by shanedwilson** [comment]
I just made it 5em on my band page styling and it's pretty stupid. In a middle school boy good way.

**Comment by shanedwilson** [comment]
Oh, and one more tiny thing, can you put a title in your  head? Right now it's still the generic 'Page Title.'

**Comment by Shijax** [comment]
👍

**Pull request merged**
