### PR TITLE
Added Background Image, Added some spacing in text. 

### PR DESCRIPTION
**Pull request by Shijax**
Still working on a more functional way to present PTD, may look at table, but want to commit bgimage and some formatting changes like new navbar and such.

### CODE REVIEW

**Comment by shanedwilson** [comment]
killer. make bg image full screen and make your footer stick to the bottom. cheers

**Comment by shanedwilson** [comment]
Looks great. I think this would pass as better than MVP, but if you want to test the scrolling stuff, you could style the events to have some margin and be a touch bigger to take up more space.

**Comment by Shijax** [comment]
Scrolling not working, but added more MVPs and made text different color so easier to ready than black with darker background image.

**Comment by shanedwilson** [comment]
👍

**Comment by acumberlander** [comment]
👍

**Pull request merged**
