### PR TITLE
added band page footer

### PR DESCRIPTION
**Pull request by shanedwilson**
band members page should show footer.

until print to dom conflict is resolved, comment out the albumBuilder function call if the band member page isn't loading correctly.

### CODE REVIEW

**Comment by Shijax** [comment]
👍

**Comment by shanedwilson** [comment]
Please check the functionality of the discography page and members page working as expected too, please. I know it's a separate ticket, but it's in this code.

**Comment by Shijax** [comment]
👍

**Comment by acumberlander** [comment]
👍 I don't understand the blank else statement but... It works! lol

**Pull request merged**
