### PR TITLE
Ac disc css

### PR DESCRIPTION
**Pull request by acumberlander**
Check for the following:
- background image added
Should look like this:
image

### CODE REVIEW

**Comment by shanedwilson** [comment]
Looking gooooooood! Can we stick with the heavy metal font family for the album titles and roboto for the song titles?

Like this:     <link href="https://fonts.googleapis.com/css?family=Metal+Mania|Roboto" rel="stylesheet">

**Comment by shanedwilson** [comment]
Looking killer, man. Can you center up the 'Discography' header and style it so it stands out from the background image? NavBar is still styled for the old navbar code. The master code has MITB in the metal font.

**Comment by shanedwilson** [comment]
👍

**Comment by Shijax** [comment]
👍

**Comment by Feven90** [comment]
:+1:

**Pull request merged**
